spring:
  application:
    name: turbine

server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}/eureka/
  instance:
    preferIpAddress: true
    ip-address: ${DOCKER_HOST_IP}
    non-secure-port: 7001

turbine:
  clusterNameExpression: new String('default')
  appConfig: API-GATEWAY
