bidcommandside:
  extends:
    file: docker-compose-common.yml
    service: bidcommandside
  volumes:
    - ./bid-service/bid-service-command-web/target:/app

bidqueryside:
  extends:
    file: docker-compose-common.yml
    service: bidqueryside
  volumes:
    - ./bid-view/bid-view-query-web/target:/app
  links:
    - mongodb

itemcommandside:
  extends:
    file: docker-compose-common.yml
    service: itemcommandside
  volumes:
    - ./item-service/item-service-command-web/target:/app

itemqueryside:
  extends:
    file: docker-compose-common.yml
    service: itemqueryside
  volumes:
    - ./item-view/item-view-query-web/target:/app
  links:
    - mongodb

mongodb:
  extends:
    file: docker-compose-common.yml
    service: mongodb
