zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.10.0
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

eureka:
  build: ./discovery
  ports:
    - 8761:8761

kafka:
  image: eventuateio/eventuateio-local-kafka:0.10.0
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181

mysql:
  image: eventuateio/eventuateio-local-mysql:0.10.0
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw


cdcservice:
  image: eventuateio/eventuateio-local-cdc-service:0.10.0
  ports:
    - "8099:8080"
  links:
    - mysql
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

mongodb:
  extends:
    file: docker-compose-common.yml
    service: mongodb

bidcommandside:
  extends:
    file: docker-compose-common.yml
    service: bidcommandside
  volumes:
    - ./bid-service/bid-service-command-web/target:/app
  links:
    - mysql
    - kafka
    - zookeeper
  mem_limit: 16g
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
    EUREKA: ${DOCKER_HOST_IP}:8761
    DOCKER_HOST_IP: ${DOCKER_HOST_IP}

bidqueryside:
  extends:
    file: docker-compose-common.yml
    service: bidqueryside
  volumes:
    - ./bid-view/bid-view-query-web/target:/app
  links:
    - mongodb
    - mysql
    - kafka
    - zookeeper
  mem_limit: 16g
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/bids
    EUREKA: ${DOCKER_HOST_IP}:8761
    DOCKER_HOST_IP: ${DOCKER_HOST_IP}

itemcommandside:
  extends:
    file: docker-compose-common.yml
    service: itemcommandside
  volumes:
    - ./item-service/item-service-command-web/target:/app
  links:
    - mysql
    - kafka
    - zookeeper
  mem_limit: 16g
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
    EUREKA: ${DOCKER_HOST_IP}:8761
    DOCKER_HOST_IP: ${DOCKER_HOST_IP}

itemqueryside:
  extends:
    file: docker-compose-common.yml
    service: itemqueryside
  volumes:
    - ./item-view/item-view-query-web/target:/app
  links:
    - mongodb
    - mysql
    - kafka
    - zookeeper
  mem_limit: 16g
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
    SPRING_DATA_MONGODB_URI: mongodb://mongodb/items
    EUREKA: ${DOCKER_HOST_IP}:8761
    DOCKER_HOST_IP: ${DOCKER_HOST_IP}

api-gateway:
  build: ./api-gateway
  ports:
    - 9001:9001
  links:
    - mongodb
    - mysql
    - kafka
    - zookeeper
    - eureka
    - bidcommandside
    - bidqueryside
    - itemcommandside
    - itemqueryside
  mem_limit: 16g
  environment:
    EUREKA: ${DOCKER_HOST_IP}:8761
    DOCKER_HOST_IP: ${DOCKER_HOST_IP}
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

hystrix:
  build: ./hystrix-dashboard
  links:
   - eureka
  ports:
    - "7000:7000"
  mem_limit: 16g
  environment:
    EUREKA: ${DOCKER_HOST_IP}:8761
    DOCKER_HOST_IP: ${DOCKER_HOST_IP}

turbine:
  build: ./turbine
  links:
   - eureka
  ports:
    - "7001:7001"
  mem_limit: 16g
  environment:
    EUREKA: ${DOCKER_HOST_IP}:8761
    DOCKER_HOST_IP: ${DOCKER_HOST_IP}

zipkin:
  build: ./zipkin
  links:
   - eureka
  ports:
    - "9411:9411"
  mem_limit: 16g
  environment:
    EUREKA: ${DOCKER_HOST_IP}:8761
    DOCKER_HOST_IP: ${DOCKER_HOST_IP}