spring:
  application:
    name: api-gateway
#  sleuth:
#    sampler:
#      percentage: 1.0
#    web:
#      skipPattern: (^cleanup.*)
#  zipkin:
#    base-url: http://${DOCKER_HOST_IP}:9411

server:
  port: ${PORT:9001}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}/eureka/
  instance:
    preferIpAddress: true
    ip-address: ${DOCKER_HOST_IP}
    non-secure-port: 9001

zuul:
  routes:
    item-command-default:
      path: /ic/**
      serviceId: item-command-V1.9.0
      retryable: true
    item-command-v1:
      path: /ic/v1.9.0/**
      serviceId: item-command-V1.9.0
      retryable: true
    item-command-v2:
      path: /ic/v2.1.0/**
      serviceId: item-command-V2.1.0
      retryable: true
    item-view:
      path: /iv/**
      serviceId: item-view
      retryable: true
    bid-command:
      path: /bc/**
      serviceId: bid-command
      retryable: true
    bid-view:
      path: /bv/**
      serviceId: bid-view
      retryable: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

logging:
  level:
   org.springframework.web: debug

management:
  security:
    enabled: false

