spring:
  application:
    name: api-gateway
server:
  port: ${PORT:9001}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}/eureka/
  instance:
    preferIpAddress: true
    ip-address: ${DOCKER_HOST_IP}
    non-secure-port: 9001


zuul:
  routes:
    item-command:
      path: /items/**
      serviceId: item-command
      stripPrefix: false
