spring:
  application:
    name: api-gateway
server:
  port: ${PORT:9001}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}/eureka/
  instance:
    preferIpAddress: true
   #ip-address: ${DOCKER_HOST_IP}
    non-secure-port: 9001

zuul:
  routes:
    item-command:
      path: /ic/**
      serviceId: item-command
    item-view:
      path: /iv/**
      serviceId: item-view
    bid-command:
      path: /bc/**
      serviceId: bid-command
    bid-view:
      path: /bv/**
      serviceId: bid-view
