spring:
  application:
    name: item-command

server:
  port: ${PORT:8761}

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.200.10.1:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: ${DOCKER_HOST_IP}
    non-secure-port: 8083

