spring:
  application:
    name: bid-view
  sleuth:
    sampler:
      percentage: 1.0
    web:
       skipPattern: (^cleanup.*)

server:
  port: ${PORT:8082}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}/eureka/
  instance:
    preferIpAddress: true
    ip-address: ${DOCKER_HOST_IP}
    non-secure-port: 8082

logging:
  level:
   org.springframework.web: debug
