spring:
  application:
    name: item-view

server:
  port: ${PORT:8084}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}/eureka/
  instance:
    preferIpAddress: true
    ip-address: ${DOCKER_HOST_IP}
    non-secure-port: 8084
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 5
