server:
  port: 8999

#standalone
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
