spring:
  application:
    name: bid-command
#  sleuth:
#    sampler:
#      percentage: 1.0
#    web:
#      skipPattern: (^cleanup.*)
#  zipkin:
#    base-url: http://${DOCKER_HOST_IP}:9411

server:
  port: ${PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA}/eureka/
  instance:
    preferIpAddress: true
    ip-address: ${DOCKER_HOST_IP}
    non-secure-port: 8081

logging:
  level:
   org.springframework.web: debug
